import crypto from "node:crypto";
import { addMonths } from "date-fns";
import type { Context } from "koa";
import Router from "koa-router";
import { slugifyDomain } from "@shared/utils/domains";
import { parseEmail } from "@shared/utils/email";
import accountProvisioner from "@server/commands/accountProvisioner";
import type { AccountProvisionerResult } from "@server/commands/accountProvisioner";
import { createContext } from "@server/context";
import env from "@server/env";
import { AuthenticationError } from "@server/errors";
import Logger from "@server/logging/Logger";
import Collection from "@server/models/Collection";
import Team from "@server/models/Team";
import type User from "@server/models/User";
import View from "@server/models/View";
import { StateStore } from "@server/utils/passport";

/**
 * Sanitize sensitive information from objects before logging.
 * Replaces sensitive fields with [REDACTED] placeholder.
 *
 * **Validates: Requirement 9.6**
 *
 * @param data - The data object to sanitize
 * @returns A new object with sensitive fields redacted
 */
function sanitizeForLog(data: any): any {
  if (!data || typeof data !== "object") {
    return data;
  }

  const sensitiveFields = ["client_secret", "access_token", "refresh_token"];
  const sanitized = Array.isArray(data) ? [...data] : { ...data };

  for (const key of Object.keys(sanitized)) {
    if (sensitiveFields.includes(key.toLowerCase())) {
      sanitized[key] = "[REDACTED]";
    } else if (typeof sanitized[key] === "object" && sanitized[key] !== null) {
      sanitized[key] = sanitizeForLog(sanitized[key]);
    }
  }

  return sanitized;
}

import pluginEnv from "./env";

const router = new Router();

// Create StateStore instance without PKCE
const stateStore = new StateStore(false);

/**
 * Generate a random state parameter for CSRF protection.
 * Uses crypto.randomBytes(32) to generate a 64-character hex string.
 * 
 * **Validates: Requirements 1.4**
 * 
 * @returns A random 64-character hex string
 */
function generateState(): string {
  return crypto.randomBytes(32).toString("hex");
}

/**
 * Store state in session for CSRF verification.
 * Uses StateStore to handle cookie management and expiry.
 * 
 * **Validates: Requirements 1.4, 2.2**
 * 
 * @param ctx - Koa context
 * @returns Promise that resolves with the token generated by StateStore
 */
async function storeState(ctx: Context): Promise<string> {
  return new Promise((resolve, reject) => {
    stateStore.store(
      ctx,
      (err: Error | null, token?: string) => {
        if (err) {
          reject(err);
        } else if (token) {
          resolve(token);
        } else {
          reject(new Error("No token returned from StateStore"));
        }
      }
    );
  });
}

/**
 * Verify state parameter from OAuth callback matches stored value.
 * 
 * **Validates: Requirements 2.2, 2.3**
 * 
 * @param ctx - Koa context
 * @param state - The state parameter from OAuth callback
 * @returns Promise that resolves if state is valid, rejects otherwise
 */
async function verifyState(ctx: Context, state: string): Promise<void> {
  return new Promise((resolve, reject) => {
    stateStore.verify(ctx, state, (err: Error | null, valid: boolean) => {
      if (err || !valid) {
        reject(err || new Error("Invalid state parameter"));
      } else {
        resolve();
      }
    });
  });
}

/**
 * Handle OAuth2 authorization request.
 * Generates state, stores it, builds authorization URL, and redirects user to SSO.
 * 
 * **Validates: Requirements 1.1, 1.2, 1.3, 1.4, 9.2**
 * 
 * @param ctx - Koa context
 */
async function handleAuthorize(ctx: Context): Promise<void> {
  // 1. Store state in session and get the token generated by StateStore
  const state = await storeState(ctx);
  
  // 2. Build authorization URL with all required OAuth2 parameters
  const authUrl = new URL(pluginEnv.SSO_AUTH_URI);
  authUrl.searchParams.set("response_type", "code");
  authUrl.searchParams.set("client_id", pluginEnv.SSO_CLIENT_ID!);
  authUrl.searchParams.set("redirect_uri", `${env.URL}/auth/sso.callback`);
  authUrl.searchParams.set("scope", pluginEnv.SSO_SCOPES);
  authUrl.searchParams.set("state", state);
  
  const finalUrl = authUrl.toString();
  
  // 3. Log authorization request (Requirement 9.2)
  Logger.info("authentication", "SSO authorization initiated", {
    client_id: pluginEnv.SSO_CLIENT_ID,
    redirect_uri: `${env.URL}/auth/sso.callback`,
    state,
    authUrl: finalUrl,
    stateCookieSet: !!ctx.cookies.get("state"),
  });
  
  // 4. Redirect user to SSO authorization endpoint
  ctx.redirect(finalUrl);
}

/**
 * Token response interface from SSO server.
 */
interface TokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  token_type?: string;
}

/**
 * User information interface from SSO server.
 */
interface UserInfo {
  sub: string;                    // User unique identifier (required)
  preferred_username?: string;    // Username
  name?: string;                  // Display name
  email: string;                  // Email address (required)
  phone_number?: string;          // Phone number
  active?: boolean;               // Account activation status
  roles?: string[];               // System internal roles
  sso_roles?: string[];           // SSO roles for external systems
}

/**
 * Exchange authorization code for access token.
 * Makes a POST request to SSO token endpoint with all required OAuth2 parameters.
 * 
 * **Validates: Requirements 3.1, 3.2, 3.3, 3.4, 9.3**
 * 
 * @param code - The authorization code from OAuth callback
 * @param ctx - Koa context (for logging purposes)
 * @returns Promise that resolves with token data
 * @throws AuthenticationError if token exchange fails
 */
async function exchangeToken(code: string, ctx: Context): Promise<TokenResponse> {
  // Build POST request to token endpoint
  const requestBody = {
    grant_type: "authorization_code",
    code,
    redirect_uri: `${env.URL}/auth/sso.callback`,
    client_id: pluginEnv.SSO_CLIENT_ID!,
    client_secret: pluginEnv.SSO_CLIENT_SECRET!,
  };

  const response = await fetch(pluginEnv.SSO_TOKEN_URI, {
    method: "POST",
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body: new URLSearchParams(requestBody),
  });

  // Log response status code with sanitized request data (Requirement 9.3)
  Logger.info("authentication", "SSO token exchange", sanitizeForLog({
    status: response.status,
    request: requestBody,
  }));

  // Handle error responses (Requirement 9.1)
  if (!response.ok) {
    const errorText = await response.text();
    const error = new Error(`Token exchange failed: ${errorText}`);
    Logger.error("SSO token exchange failed", error, sanitizeForLog({
      status: response.status,
      error: errorText,
    }));
    throw AuthenticationError("Failed to exchange authorization code for token");
  }

  // Parse and extract token data
  const data = await response.json();
  
  return {
    access_token: data.access_token,
    refresh_token: data.refresh_token,
    expires_in: data.expires_in,
    token_type: data.token_type,
  };
}

/**
 * Fetch user information from SSO server using access token.
 * Makes a GET request to SSO userinfo endpoint with Bearer token authorization.
 * 
 * **Validates: Requirements 4.1, 4.2, 4.3, 4.4, 4.5, 7.5, 9.4, 9.5**
 * 
 * @param accessToken - The access token obtained from token exchange
 * @returns Promise that resolves with user information
 * @throws AuthenticationError if userinfo request fails or validation fails
 */
async function fetchUserInfo(accessToken: string): Promise<UserInfo> {
  // Build GET request to userinfo endpoint with Authorization header
  const response = await fetch(pluginEnv.SSO_USERINFO_URI, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  // Log response status code (Requirement 9.4)
  Logger.info("authentication", "SSO userinfo request", {
    status: response.status,
  });

  // Handle error responses (Requirement 9.1)
  if (!response.ok) {
    const errorText = await response.text();
    const error = new Error(`Userinfo request failed: ${errorText}`);
    Logger.error("SSO userinfo request failed", error, {
      status: response.status,
      error: errorText,
    });
    throw AuthenticationError("Failed to fetch user information");
  }

  // Parse user information from response
  const userInfo = await response.json();

  // Validate required field: email (Requirement 4.4)
  if (!userInfo.email) {
    const error = new Error("Email field is required but not returned");
    Logger.error("SSO user validation failed", error, {
      reason: "missing_email",
      userInfo: sanitizeForLog(userInfo),
    });
    throw AuthenticationError("Email field is required but not returned");
  }

  // Validate required field: sub (Requirement 4.5)
  if (!userInfo.sub) {
    const error = new Error("User ID (sub) is required but not returned");
    Logger.error("SSO user validation failed", error, {
      reason: "missing_sub",
      userInfo: sanitizeForLog(userInfo),
    });
    throw AuthenticationError("User ID (sub) is required but not returned");
  }

  // Validate account activation status (Requirement 7.5)
  if (userInfo.active === false) {
    const error = new Error("Account is not active");
    Logger.error("SSO user validation failed", error, {
      reason: "account_inactive",
      email: userInfo.email,
      sub: userInfo.sub,
    });
    throw AuthenticationError("Account is not active");
  }

  // Log successful authentication (Requirement 9.5)
  Logger.info("authentication", "SSO user authenticated", {
    email: userInfo.email,
    sub: userInfo.sub,
  });

  return userInfo;
}

/**
 * Provision user account based on SSO user information.
 * Creates or updates user, team, and authentication records.
 * 
 * **Validates: Requirements 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 7.1, 7.2**
 * 
 * @param ctx - Koa context
 * @param userInfo - User information from SSO server
 * @param tokenData - Token data from token exchange
 * @returns Promise that resolves with account provisioner result
 */
async function provisionAccount(
  ctx: Context,
  userInfo: UserInfo,
  tokenData: TokenResponse
): Promise<AccountProvisionerResult> {
  // 1. Parse email domain and derive subdomain (Requirements 5.5)
  const { domain } = parseEmail(userInfo.email);
  const subdomain = slugifyDomain(domain);
  
  // 2. Use name or preferred_username as display name (Requirement 5.3)
  const name = userInfo.name || userInfo.preferred_username;
  
  if (!name) {
    const error = new Error("Neither name nor preferred_username was returned");
    Logger.error("SSO account provisioning failed", error, {
      email: userInfo.email,
      sub: userInfo.sub,
    });
    throw AuthenticationError("Neither name nor preferred_username was returned");
  }
  
  // 3. Create context for accountProvisioner
  const accountCtx = createContext({
    ip: ctx.ip,
    user: ctx.state?.auth?.user,
    authType: ctx.state?.auth?.type,
  });
  
  // Log account provisioning attempt
  Logger.info("authentication", "SSO account provisioning started", {
    email: userInfo.email,
    sub: userInfo.sub,
    domain,
    subdomain,
  });
  
  // 4. Call accountProvisioner with all required parameters (Requirement 5.1)
  const result = await accountProvisioner(accountCtx, {
    team: {
      teamId: undefined, // Auto-create or find team
      name: env.APP_NAME,
      domain,
      subdomain,
    },
    user: {
      name,
      email: userInfo.email, // Requirement 5.2
      avatarUrl: null,
    },
    authenticationProvider: {
      name: "sso",
      providerId: domain,
    },
    authentication: {
      providerId: userInfo.sub, // Requirement 5.4
      accessToken: tokenData.access_token, // Requirement 5.7
      refreshToken: tokenData.refresh_token, // Requirement 5.7
      expiresIn: tokenData.expires_in,
      scopes: pluginEnv.SSO_SCOPES.split(" "),
    },
  });
  
  // 5. Store SSO roles to Authentication.scopes (Requirements 7.1, 7.2)
  if (userInfo.sso_roles) {
    // Fetch authentications from database to ensure we have the latest data
    const authentications = await (result.user as any).$get("authentications");
    const authentication = authentications.find(
      (auth: any) => auth.providerId === userInfo.sub
    );
    
    if (authentication) {
      authentication.scopes = userInfo.sso_roles;
      await authentication.save();
      
      Logger.info("authentication", "SSO roles stored", {
        email: userInfo.email,
        sub: userInfo.sub,
        roles: userInfo.sso_roles,
      });
    }
  }
  
  Logger.info("authentication", "SSO account provisioning completed", {
    email: userInfo.email,
    sub: userInfo.sub,
    userId: result.user.id,
    isNewUser: result.isNewUser,
  });
  
  return result;
}

/**
 * Establish user session after successful authentication.
 * Generates JWT token, sets cookie, and updates user's last active time.
 * 
 * **Validates: Requirements 6.1, 6.2, 6.3, 6.4**
 * 
 * @param ctx - Koa context
 * @param user - The authenticated user
 */
async function establishSession(ctx: Context, user: User): Promise<void> {
  // 1. Generate JWT token (Requirement 6.1)
  const token = user.getJwtToken();
  
  // 2. Set accessToken cookie with 90 days (3 months) expiry and sameSite=lax (Requirements 6.2, 6.3)
  ctx.cookies.set("accessToken", token, {
    httpOnly: false,
    expires: addMonths(new Date(), 3), // 90 days = 3 months
    sameSite: "lax",
  });
  
  // 3. Update user's lastActiveAt timestamp (Requirement 6.4)
  user.lastActiveAt = new Date();
  await user.save();
}

/**
 * Redirect user to appropriate page in the application.
 * Priority: default collection > recent collection > /home
 * 
 * **Validates: Requirements 6.5, 6.6, 6.7**
 * 
 * @param ctx - Koa context
 * @param user - The authenticated user
 */
async function redirectToApp(ctx: Context, user: User): Promise<void> {
  // Fetch team and related data
  const [team, collection, view] = await Promise.all([
    Team.findByPk(user.teamId),
    Collection.findFirstCollectionForUser(user),
    View.findOne({
      where: {
        userId: user.id,
      },
    }),
  ]);

  if (!team) {
    throw AuthenticationError("User team not found");
  }

  const defaultCollectionId = team.defaultCollectionId;

  // Priority 1: Redirect to default collection if set (Requirement 6.5)
  if (defaultCollectionId) {
    const defaultCollection = await Collection.findOne({
      where: {
        id: defaultCollectionId,
        teamId: team.id,
      },
    });

    if (defaultCollection) {
      ctx.redirect(`${team.url}${defaultCollection.path}`);
      return;
    }
  }

  // Check if user has viewed documents
  const hasViewedDocuments = !!view;

  // Priority 2: Redirect to first collection's recent page if no viewed documents (Requirement 6.6)
  // Priority 3: Redirect to /home if no collection or has viewed documents (Requirement 6.7)
  ctx.redirect(
    !hasViewedDocuments && collection
      ? `${team.url}${collection.path}/recent`
      : `${team.url}/home`
  );
}

/**
 * Handle OAuth2 callback from SSO server.
 * Orchestrates the complete authentication flow: state verification, token exchange,
 * user info fetching, account provisioning, session establishment, and redirection.
 * 
 * **Validates: Requirements 2.1, 2.2, 2.3, 2.4**
 * 
 * @param ctx - Koa context
 */
async function handleCallback(ctx: Context): Promise<void> {
  // 1. Extract query parameters from callback URL
  const { code, state, error, error_description } = ctx.query;

  // Log callback details for debugging
  Logger.info("authentication", "SSO callback received", {
    hasCode: !!code,
    hasState: !!state,
    hasError: !!error,
    stateCookie: ctx.cookies.get("state"),
    allCookies: Object.keys(ctx.cookies).length,
  });

  // 2. Check for error parameter (Requirement 2.4, 9.1)
  if (error) {
    const authError = new Error(error as string);
    Logger.error("SSO authorization error", authError, {
      error,
      error_description,
    });
    throw AuthenticationError(
      (error_description as string) || (error as string) || "Authorization failed"
    );
  }

  // 3. Verify state parameter for CSRF protection (Requirements 2.2, 2.3, 9.1)
  try {
    await verifyState(ctx, state as string);
  } catch (err) {
    Logger.error("SSO state verification failed", err as Error, {
      hasState: !!state,
      stateCookie: ctx.cookies.get("state"),
    });
    throw AuthenticationError("Invalid state parameter");
  }

  try {
    // 4. Exchange authorization code for access token (Requirement 3.1)
    const tokenData = await exchangeToken(code as string, ctx);

    // 5. Fetch user information using access token (Requirement 4.1)
    const userInfo = await fetchUserInfo(tokenData.access_token);

    // 6. Provision user account (create or update) (Requirement 5.1)
    const result = await provisionAccount(ctx, userInfo, tokenData);

    // 7. Establish user session (Requirement 6.1)
    await establishSession(ctx, result.user);

    // 8. Redirect user to application (Requirement 6.5)
    await redirectToApp(ctx, result.user);
  } catch (err) {
    // Log all errors during OAuth flow (Requirement 9.1)
    if (err instanceof Error && err.name !== "AuthenticationError") {
      Logger.error("SSO authentication flow failed", err, {
        step: "callback_processing",
        hasCode: !!code,
      });
    }
    throw err;
  }
}

// Register routes
router.get("sso", async (ctx) => {
  Logger.info("authentication", "SSO route hit", {
    query: ctx.query,
    cookies: Object.keys(ctx.cookies),
  });
  await handleAuthorize(ctx);
});
router.get("sso.callback", async (ctx) => {
  Logger.info("authentication", "SSO callback route hit");
  await handleCallback(ctx);
});

// Log route registration
Logger.info("plugins", "SSO routes registered", {
  routes: ["sso", "sso.callback"]
});

export default router;
export { sanitizeForLog, storeState, verifyState, handleAuthorize, handleCallback, exchangeToken, fetchUserInfo, provisionAccount, establishSession, redirectToApp };
export type { TokenResponse, UserInfo };
